# Update to reflect the URL you use when logging in to RiskSense

platform_url = ''


#  An API key generated for your user. This key will have the
#  same permissions as your user. Instructions for generating
#  an API key are found at:
#  https://help.risksense.com/generating-an-api-token

api_key = ''



#  If you are a single-client user, comment this setting alone.
#  If you are a multiclient user, uncomment the client_id
#  setting below, and specify the # the client ID that you
#  wish to work with.

client_id = 123



# JIRA Platform URL

jira_url = ''



# JIRA username

jira_username = ''



# JIRA Password or API Token

jira_password_or_api_token = ''



# JIRA connector name to be created

jira_connector_name = ''